[package]
name = "animation-replace-roblox"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.19", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
# tokio = "1.45.1"
tokio = { version = "1.45.1", features = ["full"] }
url = "2.5.4"
